In [30]:
from itertools import groupby

import pandas as pd

In [31]:
# Импортируйте pandas и загрузите датасет с кодировкой: ISO-8859-1
# Проверьте, есть ли дубликаты.
# Сколько всего отменённых транзакций? (Каждая строка считается отдельной транзакцией.)
# Оставьте только заказы, где Quantity > 0. Сколько строк осталось?
# Рассматриваются только пользователи из Germany. Количество уникальных заказов (InvoiceNo)
# Используя germany_top оставьте в датафрейме только этих пользователей.
# Какой товар добавляли в корзину чаще всего? Количество товара (Quantity) учитывать не нужно.
# Revenue = Quantity × UnitPrice
# Для каждого заказа (InvoiceNo) посчитайте: Общую стоимость заказа. ТОП-5 заказов по сумме покупки.

In [32]:
retail = pd.read_csv('retail_practice.csv', encoding = 'ISO-8859-1')

retail.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536534,22383,LUNCH BAG SUKI,2,2011-04-13 13:37:00,57.77,12033,United Kingdom
1,536587,85099B,JUMBO BAG RED,13,2011-05-10 21:38:00,59.06,12014,United Kingdom
2,536462,85099B,JUMBO BAG RED,12,2011-07-12 08:33:00,55.57,12068,France
3,536551,POST,POSTAGE,11,2011-05-20 03:20:00,39.97,12015,France
4,536624,20725,LUNCH BAG RED,7,2011-05-17 20:44:00,18.09,12016,United Kingdom

In [33]:
retail_full = retail.copy()

In [34]:
retail.dtypes

InvoiceNo          str
StockCode          str
Description        str
Quantity         int64
InvoiceDate        str
UnitPrice      float64
CustomerID       int64
Country            str
dtype: object

In [35]:
retail['InvoiceDate'] = pd.to_datetime(retail['InvoiceDate'], errors='coerce')

In [36]:
retail.dtypes

InvoiceNo                 str
StockCode                 str
Description               str
Quantity                int64
InvoiceDate    datetime64[us]
UnitPrice             float64
CustomerID              int64
Country                   str
dtype: object

In [37]:
retail_columns = retail.columns

retail_columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='str')

In [38]:
retail.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1020     True
1021     True
1022     True
1023     True
1024     True
Length: 1025, dtype: bool

In [39]:
[i for i in retail.columns if retail[i].duplicated().any()]

['InvoiceNo',
 'StockCode',
 'Description',
 'Quantity',
 'InvoiceDate',
 'UnitPrice',
 'CustomerID',
 'Country']

In [40]:
retail.tail(30)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
995,536414,85123A,WHITE HANGING HEART,12,2011-07-03 00:26:00,39.44,12093,United Kingdom
996,536556,47566,PARTY BUNTING,3,2011-03-12 23:11:00,30.41,12014,Germany
997,536460,POST,POSTAGE,12,2011-03-04 14:16:00,58.99,12111,United Kingdom
998,536420,85099B,JUMBO BAG RED,3,2011-01-10 17:05:00,22.97,12035,United Kingdom
999,536664,85123A,WHITE HANGING HEART,8,2011-01-21 08:03:00,16.33,12000,France
1000,536595,22423,REGENCY CAKESTAND,5,2011-06-03 19:35:00,33.67,12103,United Kingdom
1001,536667,23203,JUMBO BAG,2,2011-05-15 12:01:00,5.32,12106,France
1002,536527,POST,POSTAGE,6,2011-05-07 06:37:00,9.57,12072,United Kingdom
1003,536411,20725,LUNCH BAG RED,7,2010-12-26 13:54:00,34.55,12027,Netherlands
1004,536564,47566,PARTY BUNTING,2,2011-01-16 08:19:00,26.96,12097,United Kingdom
1005,536532,47566,PARTY BUNTING,11,2011-04-23 12:54:00,30.74,12074,Netherlands
1006,536687,84879,ASSORTED COLOUR BIRD,11,2011-07-10 20:01:00,44.37,12113,United Kingdom
1007,536527,22423,REGENCY CAKESTAND,7,2011-02-11 16:07:00,19.14,12016,Germany
1008,536385,85099B,JUMBO BAG RED,14,2011-05-17 12:05:00,42.81,12045,United Kingdom
1009,536665,85099B,JUMBO BAG RED,13,2011-04-18 02:02:00,45.90,12022,Germany
1010,536516,22383,LUNCH BAG SUKI,3,2011-05-03 05:56:00,54.89,12101,Netherlands
1011,536610,22745,POPPY PLAYHOUSE,13,2011-02-08 10:45:00,46.68,12058,United Kingdom
1012,536567,22383,LUNCH BAG SUKI,2,2011-03-29 14:06:00,21.72,12022,United Kingdom
1013,536585,85123A,WHITE HANGING HEART,3,2011-07-11 13:03:00,6.52,12026,Italy
1014,536452,85099B,JUMBO BAG RED,2,2011-05-17 04:44:00,23.62,12118,Italy
1015,536485,23203,JUMBO BAG,2,2011-06-10 15:01:00,19.46,12012,Netherlands
1016,536591,20725,LUNCH BAG RED,8,2011-07-15 21:17:00,13.33,12065,United Kingdom
1017,536661,84879,ASSORTED COLOUR BIRD,6,2011-07-27 22:28:00,40.70,12065,Germany
1018,536390,POST,POSTAGE,1,2011-05-28 09:09:00,51.30,12085,Germany
1019,536470,20725,LUNCH BAG RED,14,2011-04-08 03:22:00,9.78,12013,United Kingdom
1020,536487,20725,LUNCH BAG RED,2,2010-12-09 23:42:00,18.64,12090,Germany
1021,536400,85099B,JUMBO BAG RED,7,2011-02-06 11:01:00,12.54,12110,Belgium
1022,536620,22745,POPPY PLAYHOUSE,1,2011-08-10 15:13:00,35.54,12060,Germany
1023,536540,85099B,JUMBO BAG RED,8,2011-07-06 14:26:00,42.19,12047,United Kingdom
1024,536703,85099B,JUMBO BAG RED,13,2011-09-08 19:04:00,47.15,12040,Germany

In [41]:
duplicates = (retail[retail.duplicated(keep=False)]).sort_values(list(retail.columns))

duplicates

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
318,536385,85099B,JUMBO BAG RED,14,2011-05-17 12:05:00,42.81,12045,United Kingdom
1008,536385,85099B,JUMBO BAG RED,14,2011-05-17 12:05:00,42.81,12045,United Kingdom
600,536390,POST,POSTAGE,1,2011-05-28 09:09:00,51.30,12085,Germany
1018,536390,POST,POSTAGE,1,2011-05-28 09:09:00,51.30,12085,Germany
472,536400,85099B,JUMBO BAG RED,7,2011-02-06 11:01:00,12.54,12110,Belgium
1021,536400,85099B,JUMBO BAG RED,7,2011-02-06 11:01:00,12.54,12110,Belgium
368,536411,20725,LUNCH BAG RED,7,2010-12-26 13:54:00,34.55,12027,Netherlands
1003,536411,20725,LUNCH BAG RED,7,2010-12-26 13:54:00,34.55,12027,Netherlands
971,536452,85099B,JUMBO BAG RED,2,2011-05-17 04:44:00,23.62,12118,Italy
1014,536452,85099B,JUMBO BAG RED,2,2011-05-17 04:44:00,23.62,12118,Italy
496,536470,20725,LUNCH BAG RED,14,2011-04-08 03:22:00,9.78,12013,United Kingdom
1019,536470,20725,LUNCH BAG RED,14,2011-04-08 03:22:00,9.78,12013,United Kingdom
133,536485,23203,JUMBO BAG,2,2011-06-10 15:01:00,19.46,12012,Netherlands
1015,536485,23203,JUMBO BAG,2,2011-06-10 15:01:00,19.46,12012,Netherlands
702,536487,20725,LUNCH BAG RED,2,2010-12-09 23:42:00,18.64,12090,Germany
1020,536487,20725,LUNCH BAG RED,2,2010-12-09 23:42:00,18.64,12090,Germany
446,536516,22383,LUNCH BAG SUKI,3,2011-05-03 05:56:00,54.89,12101,Netherlands
1010,536516,22383,LUNCH BAG SUKI,3,2011-05-03 05:56:00,54.89,12101,Netherlands
810,536527,22423,REGENCY CAKESTAND,7,2011-02-11 16:07:00,19.14,12016,Germany
1007,536527,22423,REGENCY CAKESTAND,7,2011-02-11 16:07:00,19.14,12016,Germany
452,536527,POST,POSTAGE,6,2011-05-07 06:37:00,9.57,12072,United Kingdom
1002,536527,POST,POSTAGE,6,2011-05-07 06:37:00,9.57,12072,United Kingdom
929,536532,47566,PARTY BUNTING,11,2011-04-23 12:54:00,30.74,12074,Netherlands
1005,536532,47566,PARTY BUNTING,11,2011-04-23 12:54:00,30.74,12074,Netherlands
502,536540,85099B,JUMBO BAG RED,8,2011-07-06 14:26:00,42.19,12047,United Kingdom
1023,536540,85099B,JUMBO BAG RED,8,2011-07-06 14:26:00,42.19,12047,United Kingdom
242,536564,47566,PARTY BUNTING,2,2011-01-16 08:19:00,26.96,12097,United Kingdom
1004,536564,47566,PARTY BUNTING,2,2011-01-16 08:19:00,26.96,12097,United Kingdom
968,536567,22383,LUNCH BAG SUKI,2,2011-03-29 14:06:00,21.72,12022,United Kingdom
1012,536567,22383,LUNCH BAG SUKI,2,2011-03-29 14:06:00,21.72,12022,United Kingdom
345,536585,85123A,WHITE HANGING HEART,3,2011-07-11 13:03:00,6.52,12026,Italy
1013,536585,85123A,WHITE HANGING HEART,3,2011-07-11 13:03:00,6.52,12026,Italy
104,536591,20725,LUNCH BAG RED,8,2011-07-15 21:17:00,13.33,12065,United Kingdom
1016,536591,20725,LUNCH BAG RED,8,2011-07-15 21:17:00,13.33,12065,United Kingdom
507,536595,22423,REGENCY CAKESTAND,5,2011-06-03 19:35:00,33.67,12103,United Kingdom
1000,536595,22423,REGENCY CAKESTAND,5,2011-06-03 19:35:00,33.67,12103,United Kingdom
142,536610,22745,POPPY PLAYHOUSE,13,2011-02-08 10:45:00,46.68,12058,United Kingdom
1011,536610,22745,POPPY PLAYHOUSE,13,2011-02-08 10:45:00,46.68,12058,United Kingdom
598,536620,22745,POPPY PLAYHOUSE,1,2011-08-10 15:13:00,35.54,12060,Germany
1022,536620,22745,POPPY PLAYHOUSE,1,2011-08-10 15:13:00,35.54,12060,Germany
6,536661,84879,ASSORTED COLOUR BIRD,6,2011-07-27 22:28:00,40.70,12065,Germany
1017,536661,84879,ASSORTED COLOUR BIRD,6,2011-07-27 22:28:00,40.70,12065,Germany
49,536665,85099B,JUMBO BAG RED,13,2011-04-18 02:02:00,45.90,12022,Germany
1009,536665,85099B,JUMBO BAG RED,13,2011-04-18 02:02:00,45.90,12022,Germany
818,536667,23203,JUMBO BAG,2,2011-05-15 12:01:00,5.32,12106,France
1001,536667,23203,JUMBO BAG,2,2011-05-15 12:01:00,5.32,12106,France
262,536687,84879,ASSORTED COLOUR BIRD,11,2011-07-10 20:01:00,44.37,12113,United Kingdom
1006,536687,84879,ASSORTED COLOUR BIRD,11,2011-07-10 20:01:00,44.37,12113,United Kingdom
433,536703,85099B,JUMBO BAG RED,13,2011-09-08 19:04:00,47.15,12040,Germany
1024,536703,85099B,JUMBO BAG RED,13,2011-09-08 19:04:00,47.15,12040,Germany

In [42]:
retail = retail.drop_duplicates()
retail

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536534,22383,LUNCH BAG SUKI,2,2011-04-13 13:37:00,57.77,12033,United Kingdom
1,536587,85099B,JUMBO BAG RED,13,2011-05-10 21:38:00,59.06,12014,United Kingdom
2,536462,85099B,JUMBO BAG RED,12,2011-07-12 08:33:00,55.57,12068,France
3,536551,POST,POSTAGE,11,2011-05-20 03:20:00,39.97,12015,France
4,536624,20725,LUNCH BAG RED,7,2011-05-17 20:44:00,18.09,12016,United Kingdom
...,...,...,...,...,...,...,...,...
995,536414,85123A,WHITE HANGING HEART,12,2011-07-03 00:26:00,39.44,12093,United Kingdom
996,536556,47566,PARTY BUNTING,3,2011-03-12 23:11:00,30.41,12014,Germany
997,536460,POST,POSTAGE,12,2011-03-04 14:16:00,58.99,12111,United Kingdom
998,536420,85099B,JUMBO BAG RED,3,2011-01-10 17:05:00,22.97,12035,United Kingdom
999,536664,85123A,WHITE HANGING HEART,8,2011-01-21 08:03:00,16.33,12000,France

In [43]:
cansel_tranc = [i for i in retail.InvoiceNo if i.startswith('C')]
cansel_tranc

['C536491',
 'C536707',
 'C536707',
 'C536501',
 'C536562',
 'C536432',
 'C536432',
 'C536634',
 'C536655',
 'C536689',
 'C536530',
 'C536589',
 'C536662',
 'C536409',
 'C536617',
 'C536525',
 'C536525',
 'C536384',
 'C536572',
 'C536409',
 'C536489',
 'C536689',
 'C536589',
 'C536489',
 'C536409',
 'C536634',
 'C536496',
 'C536617',
 'C536384',
 'C536432',
 'C536572',
 'C536377',
 'C536459',
 'C536454',
 'C536589',
 'C536689',
 'C536634',
 'C536662',
 'C536655',
 'C536572',
 'C536491',
 'C536491',
 'C536655',
 'C536525',
 'C536530',
 'C536409',
 'C536374',
 'C536525',
 'C536459',
 'C536409',
 'C536491',
 'C536663',
 'C536377',
 'C536662',
 'C536374',
 'C536655',
 'C536621',
 'C536454',
 'C536366',
 'C536432',
 'C536501',
 'C536589',
 'C536525',
 'C536432',
 'C536496',
 'C536454',
 'C536366',
 'C536589',
 'C536525',
 'C536454',
 'C536406',
 'C536465',
 'C536572',
 'C536465',
 'C536489']

In [44]:
len(cansel_tranc)

75

In [45]:
# вариант без list comprehension
cansel_tranc_sum = retail.InvoiceNo.str.startswith('C').sum()
cansel_tranc_sum

np.int64(75)

In [46]:
# с выводом всего ДФ
cansel_tranc_2 = retail[retail['InvoiceNo'].str.startswith('C')]
cansel_tranc_2

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
13,C536491,20725,LUNCH BAG RED,5,2011-08-24 23:40:00,14.74,12056,United Kingdom
18,C536707,23203,JUMBO BAG,7,2011-02-23 22:58:00,8.09,12079,Germany
23,C536707,22745,POPPY PLAYHOUSE,4,2011-07-28 06:16:00,46.13,12021,Germany
59,C536501,22383,LUNCH BAG SUKI,5,2011-05-03 02:37:00,59.93,12062,Netherlands
62,C536562,84879,ASSORTED COLOUR BIRD,13,2011-02-16 23:02:00,8.01,12075,United Kingdom
...,...,...,...,...,...,...,...,...
930,C536406,POST,POSTAGE,13,2011-01-03 13:32:00,23.59,12112,Germany
938,C536465,23203,JUMBO BAG,5,2011-05-05 07:52:00,46.22,12108,United Kingdom
940,C536572,84879,ASSORTED COLOUR BIRD,13,2010-12-07 23:41:00,31.00,12097,Portugal
985,C536465,22745,POPPY PLAYHOUSE,4,2010-12-03 08:55:00,30.29,12092,United Kingdom
989,C536489,POST,POSTAGE,15,2011-06-05 04:45:00,40.75,12089,France

In [47]:
retail = retail.query('Quantity > 0').reset_index(drop=True)
retail

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536534,22383,LUNCH BAG SUKI,2,2011-04-13 13:37:00,57.77,12033,United Kingdom
1,536587,85099B,JUMBO BAG RED,13,2011-05-10 21:38:00,59.06,12014,United Kingdom
2,536462,85099B,JUMBO BAG RED,12,2011-07-12 08:33:00,55.57,12068,France
3,536551,POST,POSTAGE,11,2011-05-20 03:20:00,39.97,12015,France
4,536624,20725,LUNCH BAG RED,7,2011-05-17 20:44:00,18.09,12016,United Kingdom
...,...,...,...,...,...,...,...,...
947,536414,85123A,WHITE HANGING HEART,12,2011-07-03 00:26:00,39.44,12093,United Kingdom
948,536556,47566,PARTY BUNTING,3,2011-03-12 23:11:00,30.41,12014,Germany
949,536460,POST,POSTAGE,12,2011-03-04 14:16:00,58.99,12111,United Kingdom
950,536420,85099B,JUMBO BAG RED,3,2011-01-10 17:05:00,22.97,12035,United Kingdom
951,536664,85123A,WHITE HANGING HEART,8,2011-01-21 08:03:00,16.33,12000,France

In [48]:
customer_only_germany = retail.query('Country == "Germany"') \
    .groupby('CustomerID', as_index=False)['InvoiceNo'].nunique()

customer_only_germany

    CustomerID  InvoiceNo
0        12000          2
1        12002          3
2        12003          2
3        12004          2
4        12005          2
..         ...        ...
93       12113          3
94       12116          1
95       12117          1
96       12118          4
97       12119          1

[98 rows x 2 columns]

In [49]:
p80 = customer_only_germany['InvoiceNo'].quantile(0.8)

p80

np.float64(3.0)

In [50]:
customer_above_p80 = customer_only_germany[customer_only_germany['InvoiceNo'] > p80]

customer_above_p80

    CustomerID  InvoiceNo
8        12009          6
19       12021          4
25       12030          4
31       12039          5
38       12048          6
56       12071          4
75       12090          6
76       12092          5
82       12100          4
96       12118          4

In [51]:
germany_top = customer_above_p80.CustomerID

germany_top

8     12009
19    12021
25    12030
31    12039
38    12048
56    12071
75    12090
76    12092
82    12100
96    12118
Name: CustomerID, dtype: int64

In [52]:
top_retail_germany =retail[
    retail['CustomerID'].isin(germany_top)
].reset_index(drop=True)

top_retail_germany

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536702,47566,PARTY BUNTING,9,2011-05-21 10:52:00,57.14,12030,France
1,536466,POST,POSTAGE,1,2011-04-05 23:39:00,51.06,12009,Germany
2,C536707,22745,POPPY PLAYHOUSE,4,2011-07-28 06:16:00,46.13,12021,Germany
3,536448,22423,REGENCY CAKESTAND,2,2010-12-14 17:36:00,40.80,12048,United Kingdom
4,536657,POST,POSTAGE,14,2011-06-29 09:20:00,44.81,12090,Belgium
...,...,...,...,...,...,...,...,...
97,536492,85099B,JUMBO BAG RED,10,2011-07-19 04:12:00,16.68,12100,Germany
98,536559,20725,LUNCH BAG RED,8,2011-04-25 20:35:00,36.56,12009,United Kingdom
99,C536465,22745,POPPY PLAYHOUSE,4,2010-12-03 08:55:00,30.29,12092,United Kingdom
100,536625,23203,JUMBO BAG,11,2011-06-08 06:03:00,39.23,12118,United Kingdom
101,536502,47566,PARTY BUNTING,15,2011-06-23 06:19:00,0.88,12021,Spain

In [53]:
top_retail_germany_top_description = top_retail_germany.groupby(['StockCode', 'Description'], as_index=False)['InvoiceDate'].nunique() \
    .query('StockCode != "POST"') \
    .sort_values('InvoiceDate', ascending=False)

top_retail_germany_top_description

  StockCode           Description  InvoiceDate
7    85099B         JUMBO BAG RED           14
8    85123A   WHITE HANGING HEART           14
3     22745       POPPY PLAYHOUSE           11
4     23203             JUMBO BAG           11
2     22423     REGENCY CAKESTAND           10
6     84879  ASSORTED COLOUR BIRD           10
0     20725         LUNCH BAG RED            8
5     47566         PARTY BUNTING            7
1     22383        LUNCH BAG SUKI            4

In [54]:
retail_full ['revenue'] = retail_full.Quantity * retail_full.UnitPrice

retail_full

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,revenue
0,536534,22383,LUNCH BAG SUKI,2,2011-04-13 13:37:00,57.77,12033,United Kingdom,115.54
1,536587,85099B,JUMBO BAG RED,13,2011-05-10 21:38:00,59.06,12014,United Kingdom,767.78
2,536462,85099B,JUMBO BAG RED,12,2011-07-12 08:33:00,55.57,12068,France,666.84
3,536551,POST,POSTAGE,11,2011-05-20 03:20:00,39.97,12015,France,439.67
4,536624,20725,LUNCH BAG RED,7,2011-05-17 20:44:00,18.09,12016,United Kingdom,126.63
...,...,...,...,...,...,...,...,...,...
1020,536487,20725,LUNCH BAG RED,2,2010-12-09 23:42:00,18.64,12090,Germany,37.28
1021,536400,85099B,JUMBO BAG RED,7,2011-02-06 11:01:00,12.54,12110,Belgium,87.78
1022,536620,22745,POPPY PLAYHOUSE,1,2011-08-10 15:13:00,35.54,12060,Germany,35.54
1023,536540,85099B,JUMBO BAG RED,8,2011-07-06 14:26:00,42.19,12047,United Kingdom,337.52
1024,536703,85099B,JUMBO BAG RED,13,2011-09-08 19:04:00,47.15,12040,Germany,612.95

In [55]:
general_revenue = retail_full.groupby('InvoiceNo', as_index=False).agg({'revenue':'sum'}).rename(columns={'revenue':'TotalRevenue'}) \
    .sort_values('TotalRevenue', ascending=False).head(5)

general_revenue

    InvoiceNo  TotalRevenue
101    536481       2966.81
16     536385       2606.17
272    536668       2513.54
134    536518       2363.61
173    536559       2269.50